<?php
// $Id$

/**
 *  @file
 *  Provides jquery coda style options for Views.
 */

/**
 *  Implement hook_theme().
 */
function views_coda_theme($existing, $type, $theme, $path) {
  return array(
    'views_coda' =>  array(
      'arguments' => array(
        'view' => NULL,
        'options' => array(),
        'rows' => array(),
        'title' => '',
      ),
      'template' => 'views-coda',
    ),
  );
}

/**
 *  Implements hook_views_api().
 */
function views_coda_views_api() {
  return array(
    'api' => 2.0,
  );
}

function views_coda_preprocess_views_coda(&$vars) {
  $base = drupal_get_path('module', 'views_coda');

  drupal_add_js($base . '/js/jquery.easing.1.3.js', 'module');
  drupal_add_js($base . '/js/jquery.coda-slider-2.0.js', 'module');

  drupal_add_css($base . '/css/views_coda.css', 'module');
  drupal_add_css($base . '/css/views_coda_module.css', 'module');

  $map = array(
    'autoHeight' => 'boolean',
    'autoHeightEaseDuration' => 'int',
    'autoSlide' => 'boolean',
    'autoSlideInterval' => 'int',
    'autoSlideStopWhenClicked' => 'boolean',
    'dynamicArrows' => 'boolean',
    'dynamicArrowLeftText' => 'string',
    'dynamicArrowRightText' => 'string',
    'dynamicTabs' => 'boolean',
    'dynamicTabsAlign' => 'string',
    'dynamicTabsPosition' => 'string',
    'firstPanelToLoad' => 'int',
    'slideEaseDuration' => 'int',
    'autoHeightEaseFunction' => 'string',
    'crossLinking' => 'boolean',
    'externalTriggerSelector' => 'string',
    'panelTitleSelector' => 'string',
    'slideEaseFunction' => 'string',
  );

  $jsoptions = $vars['options'];

  if ( $jsoptions['panelTitle'] == 'count' ) {
    $jsoptions['panelTitleSelector'] = '.views-coda-count';
  }
  else if ( $jsoptions['panelTitle'] == 'grouping' ) {

  }
  else if ( $jsoptions['panelTitle'] == 'field' ) {
    $fieldindex = (int)$jsoptions['panelTitleField'];

    $fieldnames = array_keys($vars['view']->field);

    $fieldname = $fieldnames[$fieldindex];
    $field = $vars['view']->field[$fieldname];

    $jsoptions['panelTitleSelector'] = '.views-field-' . str_replace('_', '-', $fieldname) . ' .field-content';
  }

  if ( is_array($jsoptions) ) {
    foreach ( $jsoptions as $key => $value ) {
      if ( !isset($map[$key]) ) {
        unset($jsoptions[$key]);
      }
      else {
        switch ( $map[$key] ) {
          case 'boolean' :
            $jsoptions[$key] = (boolean)$value;
            break;
          case 'int' :
            $jsoptions[$key] = (int)$value;
            break;
        }
      }
    }
  }

  $json = drupal_to_js($jsoptions);

  $js = <<<EOF
$().ready(function() {
  $('#coda-slider-{$vars['id']}').codaSlider(
    $json
  );
});
EOF;

  drupal_add_js($js, 'inline');
}