<?php
// $Id$

/**
 *  @file
 *  Provides jquery coda style options for Views.
 */

/**
 *  Implement hook_theme().
 */
function views_coda_theme($existing, $type, $theme, $path) {
  return array(
    'views_coda' =>  array(
      'arguments' => array(
        'view' => NULL,
        'options' => array(),
        'rows' => array(),
        'title' => '',
      ),
      'template' => 'views-coda',
    ),
  );
}

/**
 *  Implements hook_views_api().
 */
function views_coda_views_api() {
  return array(
    'api' => 2.0,
  );
}

function views_coda_preprocess_views_coda(&$vars) {

}